# This should be done by the apache role as well
# Remove once https://github.com/geerlingguy/ansible-role-apache/issues/81 is resolved
- name: Remove default vhosts.
  file:
    path: "{{ apache_conf_path }}/vhosts.conf"
    state: absent
  with_items:
    - vhosts.conf
    - userdir.conf
    - welcome.conf
  notify: restart apache
  when: apache_remove_default_vhost

- name: Enable dispatcher module.
  copy:
    dest: "{{ apache_server_root }}/conf.modules.d/01-dispatcher.conf"
    content: "LoadModule dispatcher_module modules/mod_dispatcher.so"
  notify: restart apache

- name: Install SELinux Python dependencies.
  package:
    name: libsemanage-python
    state: present

- name: Configure SELinux to allow Apache to create outbound connections.
  seboolean:
    name: httpd_can_network_connect
    state: yes
    persistent: yes
  when: ansible_selinux.status == "enabled"
