---
- name: Get installed version of Apache.
  shell: "apachectl -v"
  register: _apache_version

- name: Create apache_version variable.
  set_fact:
    apache_version: "{{ _apache_version.stdout.split()[2].split('/')[1] }}"

- name: Build Apache version filename token.
  set_fact:
    dispatcher_apache_version: "apache{{ apache_version | regex_replace('(\\d+\\.\\d+).*', '\\1') }}"

- name: Build Dispatcher filenames.
  set_fact:
    dispatcher_tarball_tokens:
      - "dispatcher"
      - "{{ dispatcher_apache_version }}"
      - "{{ ansible_system | lower }}"
      - "{{ ansible_architecture | regex_replace('_', '-')}}"
    dispatcher_module_filename: "dispatcher-{{ dispatcher_apache_version }}-{{ dispatcher_version}}.so"

- name: Add SSL filename token.
  set_fact:
    dispatcher_tarball_tokens: "{{ dispatcher_tarball_tokens + ['ssl'] }}"
  when: dispatcher_ssl_support

- name: Build dispatcher tarball name.
  set_fact:
    dispatcher_tarball_name: "{{ dispatcher_tarball_tokens | join('-') }}-{{ dispatcher_version}}.tar.gz"
