---
- name: Build Dispatcher SHA1 checksum string.
  set_fact:
    _aem_dispatcher_tarball_checksum: "sha1:{{ aem_dispatcher_tarball_sha1 }}"
  when: aem_dispatcher_tarball_sha1 is defined

- name: Download Dispatcher tarball from URL.
  get_url:
    url: "{{ aem_dispatcher_url }}"
    dest: "{{ aem_dispatcher_download_path }}/{{ aem_dispatcher_tarball_name }}"
    url_username: "{{ aem_dispatcher_url_username | default(omit) }}"
    url_password: "{{ aem_dispatcher_url_password | default(omit) }}"
    checksum: "{{ _aem_dispatcher_tarball_checksum | default(omit) }}"
